### ISSUE TITLE
Windows configure proceeds even if wrong LLVM version found

### ISSUE THREAD

**Issue by shoaibkamil** [halide/build_bot#170]
In setting up `win-worker-3`, we found that even though the various `llvm-` tasks hadn't been run (so e.g. LLVM13 was not installed) the Halide builds for LLVM13 proceed anyway, even though they find a different version of LLVM (in this case, installed through vcpkg).

They should probably fail, or the buildbots may need to explicitly not install llvm through vcpkg.

**Comment by alexreinking** [comment]
We're setting LLD_DIR in #171 to work around this. But this is ultimately a problem with upstream. I have an open PR with them:

https://reviews.llvm.org/D97513
